version: "3.8"

services:
  mongodb:
    image: mongo:7
    container_name: kuva-interview-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kuva_interview
    volumes:
      - mongodb_data:/data/db
    networks:
      - kuva-interview-network

volumes:
  mongodb_data:

networks:
  kuva-interview-network:
    driver: bridge
